Repository URECA-UFit/ufit-be, pull requests merged in 2025-06, with the labels that each got.

#28 Fix: 어드민 요금제 목록 조회 API Cursor 변경
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepository.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanRepository.java
  src/test/java/com/ureca/ufit/common/config/TestMongoAuditingConfig.java
  src/test/java/com/ureca/ufit/common/support/DataMongoSupport.java
  src/test/java/com/ureca/ufit/rateplan/repository/RatePlanQueryRepositoryTest.java
Labels: fix, feat

#33 Feat: 어드민 요금제 생성, 삭제
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/dto/ChatBotReviewMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/RatePlanMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/request/CreateRatePlanRequest.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/ChatBotReviewResponse.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/CreateRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/DeleteRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/RatePlanMetricsResponse.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/rateplan/exception/RatePlanErrorCode.java
  src/main/java/com/ureca/ufit/entity/RatePlan.java
Labels: feat

#34 Test: 어드민 요금제 목록 API 단위 테스트
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/entity/RatePlan.java
  src/test/java/com/ureca/ufit/common/fixture/RatePlanFixture.java
  src/test/java/com/ureca/ufit/rateplan/repository/RatePlanQueryRepositoryTest.java
Labels: feat, test, refactor

#32 Feat: 채팅방 생성 및 아이디 조회 API
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChaBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/ChatRoomMapper.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/response/ChatRoomCreateResponse.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotMessageRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatRoomRepository.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatRoomService.java
  src/main/java/com/ureca/ufit/domain/user/repository/UserRepository.java
  src/main/java/com/ureca/ufit/entity/ChatRoom.java
  src/main/java/com/ureca/ufit/entity/User.java
  src/main/java/com/ureca/ufit/global/auth/filter/JwtFilter.java
  src/test/java/com/ureca/ufit/chatbot/repository/ChatBotMessageRepositoryTest.java
  src/test/java/com/ureca/ufit/chatbot/service/ChatRoomServiceTest.java
  src/test/java/com/ureca/ufit/common/fixture/UserFixture.java
Labels: feat, test

#40 Feat: 챗봇 리뷰 저장 API
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/dto/ChatBotReviewMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/RatePlanMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/request/CreateRatePlanRequest.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/CreateRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/DeleteRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/RatePlanMetricsResponse.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChaBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/request/CreateChatBotReviewRequest.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/response/CreateChatBotReviewResponse.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/response/QuestionSummaryDto.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewRepository.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotMessageService.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotReviewService.java
  src/main/java/com/ureca/ufit/domain/rateplan/exception/RatePlanErrorCode.java
  src/main/java/com/ureca/ufit/domain/user/controller/UserController.java
  src/main/java/com/ureca/ufit/domain/user/dto/UserMapper.java
  src/main/java/com/ureca/ufit/domain/user/dto/request/LoginRequest.java
  src/main/java/com/ureca/ufit/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/ureca/ufit/domain/user/dto/response/LoginResponse.java
  src/main/java/com/ureca/ufit/domain/user/dto/response/RegisterResponse.java
  src/main/java/com/ureca/ufit/domain/user/exception/UserErrorCode.java
  src/main/java/com/ureca/ufit/domain/user/service/UserService.java
  src/main/java/com/ureca/ufit/entity/ChatBotMessage.java
  src/main/java/com/ureca/ufit/entity/ChatBotReview.java
  src/main/java/com/ureca/ufit/entity/ChatRoom.java
  src/main/java/com/ureca/ufit/entity/RatePlan.java
  src/main/java/com/ureca/ufit/entity/RefreshToken.java
  src/main/java/com/ureca/ufit/global/auth/contoller/AuthController.java
  src/main/java/com/ureca/ufit/global/auth/details/CustomUserDetails.java
  src/main/java/com/ureca/ufit/global/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/ureca/ufit/global/auth/filter/JwtFilter.java
  src/main/java/com/ureca/ufit/global/auth/filter/LoginFilter.java
  src/main/java/com/ureca/ufit/global/auth/handler/CustomLoginSuccessHandler.java
  src/main/java/com/ureca/ufit/global/auth/handler/CustomLogoutHandler.java
  src/main/java/com/ureca/ufit/global/auth/provider/LoginProvider.java
  src/main/java/com/ureca/ufit/global/auth/repository/RefreshTokenRepository.java
  src/main/java/com/ureca/ufit/global/auth/service/AuthService.java
  src/main/java/com/ureca/ufit/global/auth/service/CustomUserDetailsService.java
  src/main/java/com/ureca/ufit/global/auth/util/JwtUtil.java
  src/main/java/com/ureca/ufit/global/auth/util/SendErrorResponseUtil.java
  src/main/java/com/ureca/ufit/global/config/SecretKeyConfig.java
  src/main/java/com/ureca/ufit/global/config/SecurityConfig.java
  src/main/java/com/ureca/ufit/global/exception/CommonErrorCode.java
  src/test/java/com/ureca/ufit/chatbot/service/ChatBotReviewServiceTest.java
  src/test/java/com/ureca/ufit/common/fixture/ChatBotReviewFixture.java
  src/test/java/com/ureca/ufit/common/fixture/UserFixture.java
  src/test/java/com/ureca/ufit/user/controller/UserControllerTest.java
  src/test/java/com/ureca/ufit/user/filter/JwtFilterTest.java
  src/test/java/com/ureca/ufit/user/filter/LoginFilterTest.java
  src/test/java/com/ureca/ufit/user/provider/LoginProviderTest.java
  src/test/java/com/ureca/ufit/user/service/AuthServiceTest.java
  src/test/java/com/ureca/ufit/user/service/UserServiceTest.java
Labels: feat, test

#43 fix: 인증객체에 유저 아이디 추가
  src/main/java/com/ureca/ufit/global/auth/details/CustomUserDetails.java
  src/main/java/com/ureca/ufit/global/auth/service/CustomUserDetailsService.java
Labels: fix

#44 [Feat] 어드민 기능 챗봇 리뷰글 조회
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/ChatBotReviewResponse.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewQueryRepository.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewRepository.java
  src/main/java/com/ureca/ufit/entity/ChatBotReview.java
  src/test/java/com/ureca/ufit/chatbot/repository/ChatBotReviewRepositoryTest.java
  src/test/java/com/ureca/ufit/common/fixture/ChatBotReviewFixture.java
Labels: feat, test

#50 feat: swagger 추가 및 관심사 분리
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminControllerApiSpec.java
  src/main/java/com/ureca/ufit/domain/admin/dto/request/CreateRatePlanRequest.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/ChatBotReviewResponse.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChaBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChaBotControllerApiSpec.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/request/CreateChatBotMessageRequest.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/request/CreateChatBotReviewRequest.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewQueryRepository.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotReviewRepository.java
  src/main/java/com/ureca/ufit/domain/user/controller/UserController.java
  src/main/java/com/ureca/ufit/domain/user/controller/UserControllerApiSpec.java
  src/main/java/com/ureca/ufit/domain/user/dto/request/RegisterRequest.java
  src/main/java/com/ureca/ufit/entity/ChatBotReview.java
  src/main/java/com/ureca/ufit/global/auth/details/CustomUserDetails.java
  src/test/java/com/ureca/ufit/chatbot/repository/ChatBotReviewRepositoryTest.java
  src/test/java/com/ureca/ufit/common/fixture/ChatBotReviewFixture.java
Labels: feat

#53 Feat: swagger https(develop)/http(local) server
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminControllerApiSpec.java
  src/main/java/com/ureca/ufit/global/config/SwaggerConfig.java
Labels: feat, docs

#59 fix: cors origin 도메인 추가
  src/main/java/com/ureca/ufit/global/config/SecurityConfig.java
Labels: fix

#64 chore: cd docker compose 수정
  .github/workflows/cd.yml
Labels: chore

#72 feat: 요금제별 가입자수 확인 기능
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/dto/RatePlanMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/RatePlanMetricsItem.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/RatePlanMetricsResponse.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepository.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanRepository.java
  src/main/java/com/ureca/ufit/domain/user/repository/UserRepository.java
  src/test/java/com/ureca/ufit/admin/service/AdminServiceTest.java
Labels: feat, test

#75 test: RatePlanQueryRepository 테스트 코드 추가
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
  src/test/java/com/ureca/ufit/common/fixture/RatePlanFixture.java
  src/test/java/com/ureca/ufit/rateplan/repository/RatePlanQueryRepositoryTest.java
Labels: test

#78 [Feat] 요금제 추천 답변 api 연결
  src/main/java/com/ureca/ufit/domain/admin/controller/AdminController.java
  src/main/java/com/ureca/ufit/domain/admin/dto/response/RatePlanMetricsResponse.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChaBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/dto/response/CreateChatBotMessageResponse.java
  src/main/java/com/ureca/ufit/domain/chatbot/exception/ChatBotErrorCode.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotMessageService.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepository.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanRepository.java
  src/main/java/com/ureca/ufit/domain/user/repository/UserRepository.java
  src/test/java/com/ureca/ufit/admin/service/AdminServiceTest.java
Labels: feat

#86 fix: authorization api 리스트 수정
  src/main/java/com/ureca/ufit/global/auth/filter/JwtFilter.java
  src/main/java/com/ureca/ufit/global/config/SecurityConfig.java
Labels: fix

#87 fix: ChatBotMessageDto id필드 String 타입으로 수정
  src/main/java/com/ureca/ufit/domain/chatbot/dto/response/ChatMessageDto.java
  src/main/java/com/ureca/ufit/domain/chatbot/repository/ChatBotMessageRepositoryImpl.java
Labels: fix

#91 feat: 어드민 요금제 목록 조회 responseDto 판매/삭제 상태 필드 추가
  src/main/java/com/ureca/ufit/domain/admin/dto/response/AdminRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
Labels: feat

#89 feat: 요금제 목록 정렬 기능 추가
  src/main/java/com/ureca/ufit/domain/rateplan/controller/RatePlanController.java
  src/main/java/com/ureca/ufit/domain/rateplan/dto/response/RatePlanDetailResponse.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
Labels: feat

#97 fix: 어드민 요금제 목록 조회 시 누락된 데이터량 필드 및 타입 변경
  src/main/java/com/ureca/ufit/domain/admin/dto/response/AdminRatePlanResponse.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
Labels: fix, feat

#95 refactor: 요금제 상세 혜택 필드를 Map 구조로 변경
  src/main/java/com/ureca/ufit/domain/rateplan/controller/RatePlanController.java
  src/main/java/com/ureca/ufit/domain/rateplan/repository/RatePlanQueryRepositoryImpl.java
Labels: refactor

#102 fix: authorization api 리스트 수정
  src/main/java/com/ureca/ufit/global/config/SecurityConfig.java
Labels: fix

#105 chore: jacoco 추가
  build.gradle
Labels: feat, chore

#107 Test: 채팅방 생성, 과거 메시지 조회 controller 테스트
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotControllerApiSpec.java
  src/test/java/com/ureca/ufit/chatbot/controller/ChatBotControllerTest.java
  src/test/java/com/ureca/ufit/common/fixture/ChatBotMessageFixture.java
Labels: test

#110 refactor : 어드민 요금제 생성 임베딩 관련 리팩토링
  src/main/java/com/ureca/ufit/domain/admin/dto/RatePlanMapper.java
  src/main/java/com/ureca/ufit/domain/admin/dto/request/CallRatePlanRequest.java
  src/main/java/com/ureca/ufit/domain/admin/dto/request/CreateRatePlanRequest.java
  src/main/java/com/ureca/ufit/domain/admin/service/AdminService.java
  src/main/java/com/ureca/ufit/domain/chatbot/exception/ChatBotErrorCode.java
  src/main/java/com/ureca/ufit/entity/enums/DataCategory.java
Labels: feat, refactor

#115 chore: 모니터링 시스템
  build.gradle
  prometheus.yml
  src/main/java/com/ureca/ufit/global/auth/filter/JwtFilter.java
Labels: feat, chore

#116 chore: 배포
  build.gradle
  prometheus.yml
  src/main/java/com/ureca/ufit/global/auth/filter/JwtFilter.java
Labels: chore

#119 feat: RestTemplate + Async 추가
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotMessageService.java
  src/main/java/com/ureca/ufit/global/config/AsyncConfig.java
Labels: feat

#123 Fix: Async Return 타입 일치
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotControllerApiSpec.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotMessageService.java
Labels: fix

#128 fix: access token 만료 시 토큰 재발급이 되는 문제
  src/main/java/com/ureca/ufit/global/auth/handler/CustomLogoutHandler.java
  src/main/java/com/ureca/ufit/global/auth/util/JwtUtil.java
Labels: fix

#131 fix: AdminRatePlanResponse 필드 원시타입 -> 참조 타입으로 변경
  src/main/java/com/ureca/ufit/domain/admin/dto/response/AdminRatePlanResponse.java
Labels: fix

#133 feat: 성능 테스트를 위한 WebClient 추가
  build.gradle
  src/main/java/com/ureca/ufit/domain/chatbot/client/ChatClient.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotController.java
  src/main/java/com/ureca/ufit/domain/chatbot/controller/ChatBotControllerApiSpec.java
  src/main/java/com/ureca/ufit/domain/chatbot/service/ChatBotMessageService.java
  src/main/java/com/ureca/ufit/global/config/HttpClientConfig.java
  src/main/java/com/ureca/ufit/global/config/RestTemplateConfig.java
Labels: feat, chore
